"""
Writes a dump request file for the in-game extractor, using real tags found offline.

Entry tables are readable without keys, so the tags worth sampling can be chosen here rather than
guessed in game. Only the bodies need the running game, which is what `dump_if_requested()` is for.

Tags are drawn from one package family — `sandbox` by default, since that is where weapon and armour
art lives — so the sample is representative of the content we actually care about rather than of
whatever happens to be numerous.

Usage: python make_request.py [--family sandbox] [--classes 8] [--per-class 3]
"""
from __future__ import annotations

import collections
import re
import sys
from pathlib import Path

from tigerpkg import Package, PackageError

PACKAGES = Path(r"C:\Sunrise\packages")
REQUEST = Path(r"C:\Sunrise\bin\x64\Sunrise\dump\request.txt")
FAMILY_RE = re.compile(r"^w64_(?P<family>.+?)_[0-9a-f]{4}(_[a-z]{2})?_\d+\.pkg$", re.IGNORECASE)


def option(name: str, fallback):
    return type(fallback)(sys.argv[sys.argv.index(name) + 1]) if name in sys.argv else fallback


family_wanted = option("--family", "sandbox")
class_limit = option("--classes", 8)
per_class = option("--per-class", 3)


def patch_index(path: Path) -> int:
    tail = path.stem.rsplit("_", 1)[1]
    return int(tail) if tail.isdigit() else -1


newest: dict[str, Path] = {}
for path in PACKAGES.glob("*.pkg"):
    stem = path.stem.rsplit("_", 1)[0]
    if stem not in newest or patch_index(path) > patch_index(newest[stem]):
        newest[stem] = path

counts: collections.Counter[int] = collections.Counter()
samples: dict[int, list[tuple[int, int, str]]] = collections.defaultdict(list)

for path in sorted(newest.values()):
    m = FAMILY_RE.match(path.name)
    if not m or m["family"].lower() != family_wanted:
        continue
    try:
        pkg = Package(path)
    except PackageError:
        continue
    for entry in pkg.entries:
        if entry.size == 0 or entry.start_block >= pkg.header.block_count:
            continue
        counts[entry.reference] += 1
        if len(samples[entry.reference]) < per_class:
            samples[entry.reference].append((pkg.tag_for(entry.index), entry.size, path.name))

if not counts:
    raise SystemExit(f"no packages of family {family_wanted!r}")

print(f"family {family_wanted}: {sum(counts.values()):,} entries in {len(counts):,} classes\n")

lines = [
    "# Generated by tools/pkg/make_request.py - real tags, chosen offline from entry tables.",
    f"# Family: {family_wanted}. Bodies need the running game's block keys; tables did not.",
    "",
]
chosen = 0
for class_id, count in counts.most_common(class_limit):
    print(f"class 0x{class_id:08X}  {count:,} entries in {family_wanted}")
    lines.append(f"# class 0x{class_id:08X} - {count:,} entries in {family_wanted}")
    for tag, size, source in samples[class_id]:
        print(f"    tag 0x{tag:08X}  {size:,} bytes  {source}")
        lines.append(f"tag 0x{tag:08X}   # {size:,} bytes, {source}")
        chosen += 1
    lines.append("")

REQUEST.parent.mkdir(parents=True, exist_ok=True)
REQUEST.write_text("\r\n".join(lines), encoding="utf-8")
print(f"\nwrote {chosen} tag requests to {REQUEST}")
print("Launch the game, then: python readlog.py \"package_dump\"")
